import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer";
import WishlistProvider from "@/components/Wishlist/WishlistContext";

export const metadata: Metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

import AuthContext from "@/components/AuthContext/AuthContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <WishlistProvider>
            <Navbar />
            <div className="container mx-auto p-3">
              <Toaster />
              {children}
            </div>
            <Footer />
          </WishlistProvider>
        </AuthContext>
      </body>
    </html>
  );
}
